CREATE TABLE oppa_teachers (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  school TEXT,
  full_name TEXT NOT NULL,
  username TEXT NOT NULL,
  email TEXT,
  password TEXT NOT NULL,
  classes INTEGER,
  students INTEGER,
  date_created TIMESTAMP DEFAULT now() NOT NULL,
  date_modified TIMESTAMP
);

