create table RideSpot_posts (
    post_id integer primary key generated by default as identity,
    sport text not null,
    title text not null,
    spot_description text not null,
    spot_address text not null,
    difficulty text not null,
    security_level text not null,
    img text not null,
    modified timestamptz default now(),
    user_id integer references RideSpot_users(id) on delete cascade not null
);