CREATE TABLE oppa_worksheets (
  worksheet_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  worksheet_name TEXT NOT NULL,
  class_id integer references oppa_classes(class_id) on delete cascade not null,
  reading TEXT NOT NULL,
  animation_scroll TEXT
);