create table student_classes (
    id integer primary key generated by default as identity,
    student_id integer references oppa_students(id) on delete cascade not null,
    class_id integer references oppa_classes(class_id) on delete cascade not null,
    class_name text,
    class_password text
);